# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-14 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
    ]
