# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-14 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_question_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set([("question", "choice", "user")]),
        ),
    ]
