# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-16 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_auto_20210414_1831"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set([("question", "user")]),
        ),
    ]
